### ISSUE TITLE
No feedback on save click; can save multiple times

### ISSUE THREAD

**Issue by davideugenepratt** [davideugenepratt/wryter#74]

**Comment by ctillemans** [comment]
I started working on this just to make it easier for me to work on feature/40. The flow now is save, modal opens to add a title, and then on submit, it saves writing and then pushes the user to the dashbboard component.

  So maybe just hold up on changing things until we merge that feature.

**Comment by ctillemans** [comment]
I know you removed the title field but I wanted to use it to create slugs for the writing links. However, I ended up changing it back to  unique ID as a param anyways.

**Comment by davideugenepratt** [comment]
@ctillemans I was thinking we could just use the first few words from the writing for a slug/title. I kinda like the flow of not having to think of a title. You just write and let it fly and hit save and walk away.

Maybe what we can do is do an A/B test and check to see what works best.

**Comment by ctillemans** [comment]
@davideugenepratt yeah no worries I like your idea more. I was just using it for testing but will remove it on feature/40. For the time being, I am going to go back to using the unique id for fetching data. Let's make another feature to take care of the slug/title changes.
